<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
    <line>
      <![CDATA[Data : UserName]]>
    </line>
    <line>
      <![CDATA[Row : 1]]>
    </line>
    <line>
      <![CDATA[Test: testA is Failed & Photo is: ./photo/Fri Sep 28 01_18_02 IST 2018.png]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="28818" started-at="2018-09-27T19:47:36Z" finished-at="2018-09-27T19:48:05Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="28818" started-at="2018-09-27T19:47:36Z" finished-at="2018-09-27T19:48:05Z">
      <class name="script.TestDemo">
        <test-method status="PASS" signature="openApp(java.lang.String, java.lang.String)[pri:0, instance:script.TestDemo@4667ae56]" name="openApp" is-config="true" duration-ms="24445" started-at="2018-09-27T19:47:36Z" finished-at="2018-09-27T19:48:00Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[localhost]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApp -->
        <test-method status="FAIL" signature="testA()[pri:0, instance:script.TestDemo@4667ae56]" name="testA" duration-ms="2154" started-at="2018-09-27T19:48:00Z" finished-at="2018-09-27T19:48:02Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at script.TestDemo.testA(TestDemo.java:18)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Data : UserName]]>
            </line>
            <line>
              <![CDATA[Row : 1]]>
            </line>
          </reporter-output>
        </test-method> <!-- testA -->
        <test-method status="PASS" signature="closeApp(org.testng.ITestResult)[pri:0, instance:script.TestDemo@4667ae56]" name="closeApp" is-config="true" duration-ms="2063" started-at="2018-09-27T19:48:02Z" finished-at="2018-09-27T19:48:05Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testA status=FAILURE method=TestDemo.testA()[pri:0, instance:script.TestDemo@4667ae56] output=Data : UserName]]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[Test: testA is Failed & Photo is: ./photo/Fri Sep 28 01_18_02 IST 2018.png]]>
            </line>
          </reporter-output>
        </test-method> <!-- closeApp -->
      </class> <!-- script.TestDemo -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
